Tempo\Bundle\AppBundle\Model\Message:
    exclusion_policy: ALL
    properties :
      id:
        expose: true
      content:
        expose: true
      createdAt:
        expose: true
      user:
        expose: true