backend_organization_list:
    pattern:  /
    defaults:
      _controller: TempoProjectBundle:Organization:indexAction
      _sylius:
        template: TempoProjectBundle:Backend/Organization:index.html.twig
        sortable: true
        sorting:
        id: desc
    requirements:
      _method:  GET

backend_organization_show:
    pattern:  /{slug}/show
    defaults: { _controller: TempoProjectBundle:Organization:show }
    requirements:
        _method:  GET

backend_organization_create:
     pattern:  /create
     defaults: { _controller: TempoProjectBundle:Organization:create }

backend_organization_update:
     pattern:  /{id}/update
     defaults: { _controller: TempoProjectBundle:Organization:update }

backend_organization_delete:
    pattern:  /{slug}/delete
    defaults: { _controller: TempoProjectBundle:Organization:delete }
