project_home:
    pattern:  /
    defaults: { _controller: TempoProjectBundle:Project:dashboard }

project_organization_list:
    pattern:  /{slug}/list
    defaults: { _controller: TempoProjectBundle:Project:list }

project_show:
    pattern:  /{slug}/show
    defaults: { _controller: TempoProjectBundle:Project:show }

project_new:
    pattern:  /{organization}/new
    defaults: { _controller: TempoProjectBundle:Project:new }

project_create:
    pattern:  /create
    defaults: { _controller: TempoProjectBundle:Project:create }

project_edit:
    pattern:  /{slug}/edit
    defaults: { _controller: TempoProjectBundle:Project:edit }

project_update:
    pattern:  /{slug}/update
    defaults: { _controller: TempoProjectBundle:Project:update }
    requirements: { _method: post }

project_delete:
    pattern:  /{slug}/delete
    defaults: { _controller: TempoProjectBundle:Project:delete }

project_team_add:
    pattern:  /{slug}/team/add
    defaults: { _controller: TempoProjectBundle:Team:add }

project_team_create:
    pattern:  /{slug}/team/create
    defaults: { _controller: TempoProjectBundle:Team:create }
    requirements:
        _method:  GET

project_team_delete:
    pattern:  /{slug}/team/delete
    defaults: { _controller: TempoProjectBundle:Team:delete }


project_provider_list:
    pattern:  /{slug}/provider/list
    defaults: { _controller: TempoProjectBundle:Provider:list }

project_provider_new:
    pattern:  /{slug}/provider/new
    defaults: { _controller: TempoProjectBundle:Provider:new }