user_autocomplete:
    type:         rest
    defaults:
      version:  internal
    prefix:       api/{version}/
    resource: Tempo\Bundle\UserBundle\Controller\Api\Rest\UserController

user_list:
    pattern:  /user/list
    defaults: { _controller: TempoUserBundle:Default:list }

user_notification:
    type:         rest
    defaults:
      version:  v1
    prefix:       api/{version}/
    resource: Tempo\Bundle\UserBundle\Controller\NotificationController

tempo_user_notification:
    resource: "@TempoUserBundle/Resources/config/routing/notification.yml"
    prefix: /notifications

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

tempo_user_profile:
    resource: "@TempoUserBundle/Resources/config/routing/profile.yml"
    prefix: /profile

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password

user_backend:
    resource: "@TempoUserBundle/Resources/config/routing/backend/user.yml"
    prefix: /admin/users
