# Sensiolabs Insight configuration

global_exclude_dirs:
    - vendor
    - web
    - docker
    - bin

pre_composer_script: |
    #!/bin/bash

    cp app/config/parameters.yml.dist app/config/parameters.yml
    sed -i -e "s/database_user:.*/database_user: root/" app/config/parameters.yml
    sed -i -e "s/database_password:.*/database_password: Secr3t/" app/config/parameters.yml

post_composer_script: |
    #!/bin/bash

    ./app/console doctrine:database:create --no-interaction
    ./app/console doctrine:schema:create --no-interaction
    ./app/console doctrine:fixtures:load --no-interaction

exclude_patterns:
    - app/autoload.php
    - app/check.php
    - app/SymfonyRequirements.php

rules:
    symfony.web_config_should_not_be_present:
        enabled: false
