image: symfony2
env:
  - SYMFONY_ENV=prod
writable:
    - app/logs
    - app/cache
    - web/uploads
    
build:
   - apt-get update -y
   - apt-get install -y software-properties-common python-software-properties python g++ make
   - apt-add-repository ppa:chris-lea/node.js
   - apt-get update -y
   - apt-get install -y nodejs
   - npm install -g bower less@1.7 uglifyjs uglifycss
   - npm install
   - bower install --allow-root
   - mysqladmin create tempo
   - composer install --ansi --no-progress --dev --prefer-dist --no-interaction
   - app/console doctrine:schema:update --force
   - app/console doctrine:fixtures:load --env=dev --no-interaction
   - app/console assets:install web/
   - app/console assetic:dump
