language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - SYMFONY_VERSION=origin/2.1 DB=mysql

before_script:
  - echo "Starting install" > install.log

  # Setup Database
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS tempo_demo;'; fi" >> install.log

  # Setup code

  - composer self-update
  - composer install --dev --prefer-source --no-interaction
  - app/console doctrine:database:create --env=test > /dev/null
  - app/console doctrine:schema:create --env=test > /dev/null
  - mkdir -p app/cache app/logs
  - sudo chmod -R 777 app/cache app/logs


script:
    - phpunit -c app/
    - ./bin/behat