language: php

php:
  - 5.4
  - 5.5

before_script:
    - echo "Starting install" > install.log

    - cp behat.yml.dist behat.yml

    # Composer
    - composer self-update
    - composer install --prefer-source

    # For KnpSnappy
    - wget https://wkhtmltopdf.googlecode.com/files/wkhtmltopdf-0.11.0_rc1-static-amd64.tar.bz2 --output-document=wkhtmltopdf.tar.bz2
    - tar -jxvf wkhtmltopdf.tar.bz2
    - sudo mv wkhtmltopdf-amd64 /usr/bin/wkhtmltopdf

    # Selenium
    - sh -e /etc/init.d/xvfb start && export DISPLAY=:99 && wget http://selenium.googlecode.com/files/selenium-server-standalone-2.33.0.jar
    - java -jar selenium-server-standalone-2.33.0.jar > /dev/null &
    - sleep 5

    # Install database
    - php app/console do:da:cr -e=test > /dev/null
    - php app/console do:sc:cr -e=test > /dev/null
    - php app/console do:fi:lo --no-interaction -e=test > /dev/null

    # Loading web server for selenium
    - php app/console server:run > error.log &


script:
    - phpunit -c app/
    - ./bin/behat -fprogress --verbose