language: php

php:
  - 5.3

env:
  - SYMFONY_VERSION=origin/2.1 DB=mysql

before_script:
  - echo "Starting install" > install.log

  # Setup nginx
  - sudo apt-get -qq install nginx spawn-fcgi supervisor >> install.log
  - php-cgi -b 127.0.0.1:9350 &
  - sudo nginx -c tests/travis/nginx.conf -p "$PWD/"

  # Setup Database
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS tempo_demo;'; fi" >> install.log

  # Setup code
  - rm -rf .git && git init && git add --all && git commit --quiet -m "Initial commit (from the Tempo Sandbox)" >> install.log
    - wget http://getcomposer.org/composer.phar
  - php composer.phar install >> install.log
  - git add --all && git commit --quiet -m "add submodules" >> install.log
  - php tests/travis/build_bootstrap.php >> install.log

  # Setup fixtures
  - cp tests/travis/parameters.yml app/config/parameters.yml >> install.log
  - php load_data.php >> install.log