language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm-nightly
  - 7.0

matrix:
    allow_failures:
        - php: hhvm-nightly
        - php: 7.0

before_install:
    - sudo apt-get update

before_script:
    - if [[ $TRAVIS_PHP_VERSION != 'hhvm' && $TRAVIS_PHP_VERSION != 'hhvm-nightly' ]]; echo "zend.enable_gc = 0" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

    - cp behat.yml.dist behat.yml

    - npm install
    - npm -v
    - bower -version
    - bower update --config.interactive=false --allow-root

    # Composer
    - composer self-update
    - composer install --prefer-source --no-interaction

    # For KnpSnappy
    - wget https://wkhtmltopdf.googlecode.com/files/wkhtmltopdf-0.11.0_rc1-static-amd64.tar.bz2 --output-document=wkhtmltopdf.tar.bz2
    - tar -jxvf wkhtmltopdf.tar.bz2
    - sudo mv wkhtmltopdf-amd64 /usr/bin/wkhtmltopdf

    # Selenium
    - sh -e /etc/init.d/xvfb start && export DISPLAY=:99 && wget http://selenium.googlecode.com/files/selenium-server-standalone-2.33.0.jar
    - java -jar selenium-server-standalone-2.33.0.jar > /dev/null &
    - sleep 5

    # Install database
    - php app/console doctrine:database:create --env=test
    - php app/console doctrine:schema:create --env=test
    - php app/console doctrine:fixtures:load --no-interaction --env=test

    # Loading web server for selenium
    - node bin/server.js > error.log &
    - php app/console server:run > error.log &


script:
    - ./bin/phpunit -c app/
    - ./bin/behat -fprogress --verbose
