_project:
  resource: "@TempoProjectBundle/Resources/config/routing/project.yml"
  prefix:   /project

_project_settings:
    pattern: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.settings:updateAction
        namespace: general
        template: TempoMainBundle:Backend/Settings:general.html.twig

_project_api:
  type: rest
  prefix:   /api/{version}/project
  resource: "@TempoProjectBundle/Resources/config/routing/project_api.yml"
  defaults:
      version: v1

_organization:
  resource: "@TempoProjectBundle/Resources/config/routing/organization.yml"
  prefix:   /organization

_organization_api:
  type: rest
  resource: "@TempoProjectBundle/Resources/config/routing/organization_api.yml"
  prefix:   /api/{version}/organization
  defaults:
      version: v1

_timesheet:
  resource: "@TempoProjectBundle/Resources/config/routing/timesheet.yml"
  prefix:   /timesheet

_timesheet_api:
  type: rest
  prefix:   /api/{version}/timesheet
  resource: "@TempoProjectBundle/Resources/config/routing/timesheet_api.yml"
  defaults:
      version: v1