_project:
  resource: "@TempoProjectBundle/Resources/config/routing/project.yml"
  prefix:   /project

_organization:
  resource: "@TempoProjectBundle/Resources/config/routing/organization.yml"
  prefix:   /organization

_timesheet:
  resource: "@TempoProjectBundle/Resources/config/routing/timesheet.yml"
  prefix:   /timesheet
