help:
    pattern: /help
    defaults: { _controller: TempoMainBundle:Frontend\Default:help }

backend:
    pattern: /admin
    defaults: { _controller: TempoMainBundle:Backend\Dashboard:main }

main_room:
  type: rest
  resource: "@TempoMainBundle/Resources/config/routing/room.yml"

main_room_api:
  type: rest
  prefix:   /api/{version}
  resource: "@TempoMainBundle/Resources/config/routing/room_api.yml"
  defaults:
      version: v1

main_chat:
  type: rest
  resource: "@TempoMainBundle/Resources/config/routing/chat.yml"

main_chat_api:
  type: rest
  prefix:   /api/{version}
  resource: "@TempoMainBundle/Resources/config/routing/chat_api.yml"
  defaults:
      version: v1


#Backend
tempo_setting_backend:
    resource: "@TempoMainBundle/Resources/config/routing/backend/settings.yml"
    prefix: /admin/settings