settings:
    pattern: /settings
    defaults: { _controller: TempoMainBundle:Default:settings }

help:
    pattern: /help
    defaults: { _controller: TempoMainBundle:Default:help }

main_chat:
  type: rest
  resource: "@TempoMainBundle/Resources/config/routing/chat.yml"