imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: imagine.yml }
    - { resource: @TempoAppBundle/Resources/config/app/main.yml }
    - { resource: @TempoAppBundle/Resources/config/app/api.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] }
    default_locale: %locale%
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources: ['bootstrap_3_layout.html.twig']

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    TempoAppBundle:
                        prefix: Tempo\Bundle\AppBundle\Model
                        is_bundle: true
                        type: xml
                        alias: TempoAppBundle
                    StofDoctrineExtensionsBundle: true
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../src/Tempo/Bundle/AppBundle/Model/"
                        alias: GedmoLoggable
                        is_bundle: false

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    port:      %mailer_port%
    spool:     { type: memory }

# app/config/config.yml
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            tree: true
            timestampable: true
            sluggable: true

sylius_settings:
    resources:
        parameter:
            classes:
                model: Tempo\Bundle\AppBundle\Model\Parameter
