imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: fos_user.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] }
    default_locale: %locale%
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            StofDoctrineExtensionsBundle: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%



stof_doctrine_extensions:
    default_locale: %locale%
    translation_fallback: true
    orm:
        default:
          loggable: false
          sluggable: true
          timestampable: true
          translatable: false
          tree: false

knp_time: ~  # Enable the helper for use in templates

ikimea_ck_editor:
    lang : fr
    src : /bundles/ikimeackeditor/js/ckeditor/
    skin: kama
    toolbar:
      - ['Format']
      - ['Bold','Italic']
      - ['Outdent','Indent','Blockquote']
      - ['NumberedList','BulletedList']
      - ['-','Link','Unlink','Anchor','-','Table']
      - ['Maximize','Source']

sonata_seo:
  default:  sonata.seo.page.default
  title:    Project Management Software


tempo_project:
  week:
    fr :
      - Lundi
      - Mardi
      - Mecredi
      - Jeudi
      - Vendredi
      - Samedi
      - Dimanche
    en :
      - Monday
