imports:
    - { resource: config.yml }

framework:
    test: ~
    default_locale:  "en"
    session:
        storage_id: session.storage.mock_file

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        dbname:   %database_name%_test

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug