imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: imagine.yml }
    - { resource: tempo.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] }
    default_locale: %locale%
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%


# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        less:
            node: %node_bin%
            node_paths: [%node_modules%]
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar


# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            StofDoctrineExtensionsBundle: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%


sylius_settings:
    driver: doctrine/orm

liip_doctrine_cache:
    namespaces:
        sylius_settings:
            type: file_system

stof_doctrine_extensions:
    default_locale: %locale%
    translation_fallback: true
    orm:
        default:
          loggable: false
          sluggable: true
          timestampable: true
          translatable: false
          tree: false

sensio_framework_extra:
    view:
        annotations: false

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'
    routing_loader:
        default_format: json
    access_denied_listener:
        json: true
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT

knp_time: ~  # Enable the helper for use in templates


fos_user:
    db_driver: orm
    use_listener: false
    firewall_name: main
    user_class: Tempo\Bundle\UserBundle\Entity\User
    group:
        group_class: Tempo\Bundle\UserBundle\Entity\Group

fos_js_routing:
    routes_to_expose: ['get_rooms', 'get_room_messages']

hwi_oauth:
    firewall_name: main
    resource_owners:
        google:
            type:          google
            client_id:     %oauth.google.clientid%
            client_secret: %oauth.google.clientsecret%
            scope:         "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"

        github:
            type: github
            client_id:     %oauth.github.clientid%
            client_secret: %oauth.github.clientsecret%


ivory_ck_editor:
  configs:
    default:
      toolbar:
        - ['Format']
        - ['Bold','Italic']
        - ['Outdent','Indent','Blockquote']
        - ['NumberedList','BulletedList']
        - ['-','Link','Unlink','Anchor','-','Table']
        - ['Maximize','Source']

tempo_project:
  week:
    fr :
      - Lundi
      - Mardi
      - Mecredi
      - Jeudi
      - Vendredi
      - Samedi
      - Dimanche
    en :
      - Monday
      - Tuesday
      - Wednesday
      - Thursday
      - Friday
      - Saturday
      - Sunday

knp_snappy:
    pdf:
        enabled:    true
        binary:     %knp_snappy.pdf.binary%
        options:    []
    image:
        enabled:    true
        binary:     %knp_snappy.image.binary%
        options:    []

mopa_bootstrap:
    form:
        show_legend: false # default is true
        show_child_legend: false # default is true
        error_type: block # or inline which is default
        render_optional_text: false

tempo_js_configuration:
  config_to_expose: [locale]

jms_serializer:
    metadata:
      debug: "%kernel.debug%"
      auto_detection: true
      directories:
            FOSUserBundle:
              namespace_prefix: "FOS\\UserBundle"
              path: "@TempoUserBundle/Resources/config/serializer/FOSUserBundle"
