
# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

_imagine:
    resource: .
    type:     imagine

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_bazinga_exposetranslation:
    resource: "@BazingaExposeTranslationBundle/Resources/config/routing/routing.yml"

homepage:
    pattern:  /
    defaults: { _controller: TempoMainBundle:Frontend\Dashboard:main }

_tempo_users:
    resource: "@TempoUserBundle/Resources/config/routing/routing.yml"
hwi_oauth_security:
     resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
     prefix: /connect

hwi_oauth_redirect:
  resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
  prefix: /login

google_login:
  pattern: /login/check-google

_tempo_main:
    resource: "@TempoMainBundle/Resources/config/routing.yml"

_tempo_projects:
    resource: "@TempoProjectBundle/Resources/config/routing.yml"

_tempo_activity:
    resource: "@TempoActivityBundle/Resources/config/routing.yml"
    