
# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal


_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

homepage:
    path:  /
    defaults: { _controller: TempoAppBundle:Dashboard:main }
    options:
        expose: true

_tempo_users:
    resource: "@TempoAppBundle/Resources/config/routing.yml"
    
hwi_oauth_security:
     resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
     prefix: /connect

hwi_oauth_redirect:
  resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
  prefix: /login

google_login:
  path: /login/check-google

_tempo_app:
    resource: "@TempoAppBundle/Resources/config/routing.yml"
