# app/config/security.yml
security:
    acl:
      connection: default

    providers:
        tempo_user:
            id: tempo.user.user_provider.username

    encoders:
        "Tempo\Bundle\AppBundle\Model\UserInterface": sha512

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api/v
            stateless: false
            simple_preauth:
                authenticator: tempo.user.security.api_token_authenticator
        main:
            pattern: ^/
            switch_user: false
            context:     user
            form_login:
                provider: tempo_user
                login_path: /login
                check_path: /login_check
                failure_path: /login
                default_target_path: /
                use_forward:  false
                use_referer: false
            remember_me:
                key: %secret%
                name: APP_REMEMBER_ME
                lifetime: 31536000
                always_remember_me: true
                remember_me_parameter: _remember_me
            oauth:
                resource_owners:
                  google: "/login/check-google"
                  github: "/login/check-github"
                login_path: /login
                failure_path: /login
                oauth_user_provider:
                  service: tempo.user.oauth.user_provider
            logout: true
            anonymous:    true
        
    access_control:
        - { path: ^/user/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/*, role: ROLE_USER }


    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
