sylius_resource:
    resources:

      tempo.organization:
        driver: doctrine/orm
        classes:
          controller: Tempo\Bundle\ProjectBundle\Controller\Backend\Organization
          model: Tempo\Bundle\ProjectBundle\Model\Organization

      tempo.project:
         driver: doctrine/orm
         classes:
            model: Tempo\Bundle\ProjectBundle\Entity\Project

      tempo.user:
          driver: doctrine/orm
          classes:
            controller: Tempo\Bundle\UserBundle\Controller\Backend\UserController
            model: Tempo\Bundle\UserBundle\Entity\User

      tempo.group:
          driver: doctrine/orm
          classes:
            #controller: Tempo\Bundle\UserBundle\Controller\Backend\GroupController
            model: Tempo\Bundle\UserBundle\Entity\Group

