backend_organization_list:
    path:  /
    defaults:
      _controller: TempoAppBundle:Organization:indexAction
      _sylius:
        template: TempoAppBundle:Backend/Organization:index.html.twig
        sortable: true
        sorting:
        id: desc
    requirements:
      _method:  GET

backend_organization_show:
    path:  /{slug}/show
    defaults: { _controller: TempoAppBundle:Organization:show }
    requirements:
        _method:  GET

backend_organization_create:
     path:  /create
     defaults: { _controller: TempoAppBundle:Organization:create }

backend_organization_update:
     path:  /{id}/update
     defaults: { _controller: TempoAppBundle:Organization:update }

backend_organization_delete:
    path:  /{slug}/delete
    defaults: { _controller: TempoAppBundle:Organization:delete }
