backend_organization_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: tempo.backend.controller.organization:indexAction
        _sylius:
            template: TempoAppBundle:Backend/Organization:index.html.twig
            arguments: [$criteria, $sorting]

backend_organization_filter_form:
    pattern: /filter-form
    methods: [GET]
    defaults:
        _controller: tempo.backend.controller.organization:filterFormAction
        _sylius:
            form: Tempo\Bundle\AppBundle\Form\Type\Backend\Filter\OrganizationFilterType

backend_organization_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: tempo.backend.controller.organization:deleteAction
        _sylius:
            redirect: backend_organization_index