backend_project_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: tempo_backend.controller.project:indexAction
        _sylius:
            template: TempoAppBundle:Backend/Project:index.html.twig
            arguments: [$criteria, $sorting]


backend_project_filter_form:
    pattern: /filter-form
    methods: [GET]
    defaults:
        _controller: tempo_backend.controller.project:filterFormAction

backend_project_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: tempo_backend.controller.project:deleteAction
        _sylius:
            redirect: backend_project_index