backend_configuration_generale:
    path: /
    methods: [GET|POST]
    defaults:
        _controller: sylius.controller.settings:updateAction
        namespace: general
        template: TempoAppBundle:Backend/Settings:general.html.twig

backend_configuration_project:
    path: /project
    methods: [GET|POST]
    defaults:
        _controller: sylius.controller.settings:updateAction
        namespace: project
        template: TempoAppBundle:Backend/Settings:project.html.twig
