timesheet:
    path:  /
    defaults: { _controller: "TempoAppBundle:Timesheet:dashboard" }

timesheet_show:
    path:  /{id}/show
    defaults: { _controller: "TempoAppBundle:Timesheet:show" }

timesheet_new:
    path:  /new
    defaults: { _controller: "TempoAppBundle:Timesheet:new" }

timesheet_create:
    path:  /create
    defaults: { _controller: "TempoAppBundle:Timesheet:create" }
    requirements: { _method: POST }

timesheet_edit:
    path:  /{id}/edit
    defaults: { _controller: "TempoAppBundle:Timesheet:edit" }

timesheet_update:
    path:  /{id}/update
    defaults: { _controller: "TempoAppBundle:Timesheet:update" }
    requirements: { _method: POST }

timesheet_delete:
    path:  /{id}/delete
    defaults: { _controller: "TempoAppBundle:Timesheet:delete" }
    requirements: { _method: POST }
