activity_provider_ws:
    pattern: /provider/notify/{token}
    defaults:
        _controller: TempoActivityBundle:Activity:provider

activity_list:
    pattern: /activity/list/{type}/{project}
    defaults:
        _controller: TempoActivityBundle:Activity:list
    options:
      expose: true

activity_test:
    pattern: /activity/test
    defaults:
        _controller: TempoActivityBundle:Activity:test
