parameters:
    tempo.activity.manager.class: Tempo\Bundle\ActivityBundle\Entity\Activity

services:
    tempo.activity.manager:
        class: "%tempo.activity.manager.class%"
        arguments: ["@doctrine.orm.entity_manager"]
        calls:
            - [setContainer, ["@service_container"]]