admin_project_index:
    path: /
    methods: [GET]
    defaults:
        _controller: tempo.admin.controller.project:indexAction
        _sylius:
            template: TempoAppBundle:Admin/Project:index.html.twig
            arguments: [$criteria, $sorting]


admin_project_filter_form:
    path: /filter-form
    methods: [GET]
    defaults:
        _controller: tempo.admin.controller.project:filterFormAction
        _sylius:
            form: Tempo\Bundle\AppBundle\Form\Type\Admin\Filter\OrganizationFilterType

admin_project_delete:
    path: /{id}
    methods: [DELETE]
    defaults:
        _controller: tempo.admin.controller.project:deleteAction
        _sylius:
            redirect: admin_project_index