imports:
    - { resource: @TempoAppBundle/Resources/config/app/resource.yml }
    - { resource: @TempoAppBundle/Resources/config/app/admin.yml }

sylius_settings:
    driver: doctrine/orm

doctrine_cache:
    providers:
        sylius_settings:
            type: file_system

stof_doctrine_extensions:
    default_locale: %locale%
    translation_fallback: true
    orm:
        default:
          loggable: true
          sluggable: true
          timestampable: true
          translatable: false
          tree: false

sensio_framework_extra:
    view:
        annotations: false

fos_js_routing:
    routes_to_expose: ['room_list', 'room_create', 'api_message_post_message', 'api_message_get_messages', 'timesheet_create', 'api_user_current']

hwi_oauth:
    firewall_name: main
    resource_owners:
        google:
            type:          google
            client_id:     %oauth.google.clientid%
            client_secret: %oauth.google.clientsecret%
            scope:         "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
            options:
                access_type: offline
                approval_prompt: force
                display: page
                login_hint: email address
  
        github:
            type: github
            client_id:     %oauth.github.clientid%
            client_secret: %oauth.github.clientsecret%

tempo_app:
  week:
    fr :
      - Lundi
      - Mardi
      - Mecredi
      - Jeudi
      - Vendredi
      - Samedi
      - Dimanche
    en :
      - Monday
      - Tuesday
      - Wednesday
      - Thursday
      - Friday
      - Saturday
      - Sunday

knp_snappy:
    pdf:
        enabled:    true
        binary:     %knp_snappy.pdf.binary%
        options:    []
    image:
        enabled:    true
        binary:     %knp_snappy.image.binary%
        options:    []

tempo_js_configuration:
  config_to_expose: [locale]

jms_serializer:
    metadata:
      debug: "%kernel.debug%"
      auto_detection: true
