imports:
    - { resource: @TempoAppBundle/Resources/config/app/tempo.yml }

sylius_settings:
    driver: doctrine/orm

doctrine_cache:
    providers:
        sylius_settings:
            type: file_system

stof_doctrine_extensions:
    default_locale: %locale%
    translation_fallback: true
    orm:
        default:
          loggable: true
          sluggable: true
          timestampable: true
          translatable: false
          tree: false

sensio_framework_extra:
    view:
        annotations: false

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'
    routing_loader:
        default_format: json
    access_denied_listener:
        json: true
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT

fos_js_routing:
    routes_to_expose: ['room_list', 'chat_room_post_message', 'chat_room_get_messages', 'timesheet_create']

hwi_oauth:
    firewall_name: main
    resource_owners:
        google:
            type:          google
            client_id:     %oauth.google.clientid%
            client_secret: %oauth.google.clientsecret%
            scope:         "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"

        github:
            type: github
            client_id:     %oauth.github.clientid%
            client_secret: %oauth.github.clientsecret%

ivory_ck_editor:
  configs:
    default:
      skin: 'husky,/vendor/ckeditor-light-theme/'
      toolbar:
        - ['Format']
        - ['Bold','Italic']
        - ['Outdent','Indent','Blockquote']
        - ['NumberedList','BulletedList']
        - ['-','Link','Unlink','Anchor','-','Table']
        - ['Maximize','Source']

tempo_app:
  week:
    fr :
      - Lundi
      - Mardi
      - Mecredi
      - Jeudi
      - Vendredi
      - Samedi
      - Dimanche
    en :
      - Monday
      - Tuesday
      - Wednesday
      - Thursday
      - Friday
      - Saturday
      - Sunday

knp_snappy:
    pdf:
        enabled:    true
        binary:     %knp_snappy.pdf.binary%
        options:    []
    image:
        enabled:    true
        binary:     %knp_snappy.image.binary%
        options:    []

tempo_js_configuration:
  config_to_expose: [locale]

jms_serializer:
    metadata:
      debug: "%kernel.debug%"
      auto_detection: true
