sylius_resource:
  resources:
      tempo.organization:
          driver: doctrine/orm
          classes:
              model: Tempo\Bundle\AppBundle\Model\Organization
              repository: Tempo\Bundle\AppBundle\Repository\OrganizationRepository

      tempo.project:
          driver: doctrine/orm
          classes:
              model: Tempo\Bundle\AppBundle\Model\Project
              repository: Tempo\Bundle\AppBundle\Repository\ProjectRepository

      tempo.project_provider:
          driver: doctrine/orm
          classes:
              model: Tempo\Bundle\AppBundle\Model\ProjectProvider

      tempo.timesheet:
          driver: doctrine/orm
          classes:
              model: Tempo\Bundle\AppBundle\Model\Timesheet
              repository: Tempo\Bundle\AppBundle\Repository\TimesheetRepository

      tempo.user:
          driver: doctrine/orm
          classes:
              model: Tempo\Bundle\AppBundle\Model\User
              repository: Tempo\Bundle\AppBundle\Repository\UserRepository

      tempo.user_email:
          driver: doctrine/orm
          classes:
              model: Tempo\Bundle\AppBundle\Model\UserEmail
      
      tempo.activity:
          driver: doctrine/orm
          classes:
              model: Tempo\Bundle\AppBundle\Model\Activity
              repository: Tempo\Bundle\AppBundle\Repository\ActivityRepository

      tempo.activity_provider:
          driver: doctrine/orm
          classes:
              model: Tempo\Bundle\AppBundle\Model\ActivityProvider
              repository: Tempo\Bundle\AppBundle\Repository\ActivityProviderRepository

      tempo.access:
          driver: doctrine/orm
          classes:
              model: Tempo\Bundle\AppBundle\Model\Access
              repository: Tempo\Bundle\AppBundle\Repository\AccessRepository

      tempo.notification:
          driver: doctrine/orm
          classes:
              model: Tempo\Bundle\AppBundle\Model\Notification
              repository: Tempo\Bundle\AppBundle\Repository\NotificationRepository

      tempo.room:
          driver: doctrine/orm
          classes:
              model: Tempo\Bundle\AppBundle\Model\Room
              repository: Tempo\Bundle\AppBundle\Repository\RoomRepository

      tempo.message:
          driver: doctrine/orm
          classes:
              model: Tempo\Bundle\AppBundle\Model\Message
              repository: Tempo\Bundle\AppBundle\Repository\MessageRepository

      tempo.comment:
          driver: doctrine/orm
          classes:
              model: Tempo\Bundle\AppBundle\Model\Comment
              repository: Tempo\Bundle\AppBundle\Repository\CommentRepository
