backend_user_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: tempo_backend.controller.user:indexAction
        _sylius:
            template: TempoUserBundle:Backend/User:index.html.twig
            #method: createFilterPaginator
            arguments: [$criteria, $sorting]

backend_user_filter_form:
    pattern: /filter-form
    methods: [GET]
    defaults:
        _controller: tempo_backend.controller.user:filterFormAction
        _sylius:
            template: TempoUserBundle:Backend/User:filterForm.html.twig

backend_user_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: tempo_backend.controller.user:createAction
        _sylius:
            template: TempoUserBundle:Backend/User:create.html.twig
            redirect: backend_user_show

backend_user_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: tempo_backend.controller.user:updateAction
        _sylius:
            template: TempoUserBundle:Backend/User:update.html.twig
            redirect: backend_user_show

backend_user_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: tempo_backend.controller.user:deleteAction
        _sylius:
            redirect: backend_user_index

backend_user_show:
    pattern: /{id}
    methods: [GET]
    defaults:
        _controller: tempo_backend.controller.user:showAction
        _sylius:
            template: TempoUserBundle:Backend/User:show.html.twig
            redirect: backend_user_show