notification_dashboard:
    pattern:  /
    defaults: { _controller: "TempoUserBundle:Notification:dashboard" }

notification_read:
    pattern:  /{date}/show
    defaults: { _controller: "TempoUserBundle:Notification:state" }

notification_unread:
    pattern:  /{date}/show
    defaults: { _controller: "TempoUserBundle:Notification:state" }

notification_clear:
    pattern:  /clear
    defaults: { _controller: "TempoUserBundle:Notification:clear" }