admin:
    path: /admin
    defaults: { _controller: TempoAppBundle:Admin/Dashboard:main }

_user:
  resource: "@TempoAppBundle/Resources/config/routing/users.yml"

room:
  resource: "@TempoAppBundle/Resources/config/routing/room.yml"
  prefix:   /room

room_api:
  type: rest
  prefix:   /api/{version}/room
  resource: "@TempoAppBundle/Resources/config/routing/room_api.yml"
  defaults:
      version: v1

message_api:
  type: rest
  prefix:   /api/{version}
  resource: "@TempoAppBundle/Resources/config/routing/message_api.yml"
  defaults:
      version: v1

_project:
  resource: "@TempoAppBundle/Resources/config/routing/project.yml"
  prefix:   /project

_project_api:
  type: rest
  prefix:   /api/{version}/project
  resource: "@TempoAppBundle/Resources/config/routing/project_api.yml"
  defaults:
      version: v1

_project_admin:
    resource: "@TempoAppBundle/Resources/config/routing/admin/project.yml"
    prefix: /admin/project

_organization:
  resource: "@TempoAppBundle/Resources/config/routing/organization.yml"
  prefix:   /organization

_organization_api:
  type: rest
  resource: "@TempoAppBundle/Resources/config/routing/organization_api.yml"
  prefix:   /api/{version}/organization
  defaults:
      version: v1

_organization_admin:
    resource: "@TempoAppBundle/Resources/config/routing/admin/organization.yml"
    prefix: /admin/organization

_timesheet:
  resource: "@TempoAppBundle/Resources/config/routing/timesheet.yml"
  prefix:   /timesheet

_timesheet_api:
  type: rest
  prefix:   /api/{version}/timesheet
  resource: "@TempoAppBundle/Resources/config/routing/timesheet_api.yml"
  defaults:
      version: v1

_activity:
 resource: "@TempoAppBundle/Resources/config/routing/activity.yml"

_prodiver_api:
  type: rest
  prefix:   /api/{version}/provider
  resource: "@TempoAppBundle/Resources/config/routing/provider_api.yml"
  defaults:
      version: v1

_comment:
  resource: "@TempoAppBundle/Resources/config/routing/comment.yml"
  prefix:   /comment

_emails:
  resource: "@TempoAppBundle/Resources/config/routing/userEmail.yml"
  prefix: /user/email

#Admin
setting_admin:
    resource: "@TempoAppBundle/Resources/config/routing/admin/settings.yml"
    prefix: /admin/settings


