chatRoom_rooms:
    type:     rest
    resource: Tempo\Bundle\MainBundle\Controller\Frontend\RoomController

chatRoom_messages:
    type:     rest
    parent: chatRoom_rooms
    resource: Tempo\Bundle\MainBundle\Controller\Frontend\MessagesController