chat_room_api:
    type:     rest
    resource: Tempo\Bundle\MainBundle\Controller\Frontend\RoomController
    prefix: /api
    name_prefix: api_room_
    options:
        expose: true

chat_room_messages_api:
    type:     rest
    parent: chat_room_api
    name_prefix: api_room_message_
    resource: Tempo\Bundle\MainBundle\Controller\Frontend\MessagesController
    options:
        expose: true