client_show:
    pattern:  /{slug}/show
    defaults: { _controller: TempoProjectBundle:Client:show }
    requirements:
        _method:  GET

client_new:
    pattern:  /new
    defaults: { _controller: TempoProjectBundle:Client:new }

client_create:
     pattern:  /create
     defaults: { _controller: TempoProjectBundle:Client:create }

client_edit:
    pattern:  /{slug}/edit
    defaults: { _controller: TempoProjectBundle:Client:edit }
    requirements:
        _method:  GET

client_update:
     pattern:  /{id}/update
     defaults: { _controller: TempoProjectBundle:Client:update }

client_delete:
    pattern:  /{slug}/delete
    defaults: { _controller: TempoProjectBundle:Client:delete }

client_team_add:
    pattern:  /{slug}/team/add
    defaults: { _controller: TempoProjectBundle:Team:add }

client_team_create:
    pattern:  /{slug}/team/create
    defaults: { _controller: TempoProjectBundle:Team:create }
    requirements:
        _method:  GET

client_team_delete:
    pattern:  /{slug}/team/delete
    defaults: { _controller: TempoProjectBundle:Team:delete }
