organization_create:
    pattern:  /create
    defaults: { _controller: TempoProjectBundle:Organization:create }
    requirements:
        _method:  GET|POST

organization_update:
     pattern:  /{slug}/update
     defaults: { _controller: TempoProjectBundle:Organization:update }
     requirements:
        _method:  GET|POST

organization_delete:
    pattern:  /{slug}/delete
    defaults: { _controller: TempoProjectBundle:Organization:delete }

organization_team_add:
    pattern:  /{slug}/team/add
    defaults: { _controller: TempoProjectBundle:Team:add }

organization_team_create:
    pattern:  /{slug}/team/create
    defaults: { _controller: TempoProjectBundle:Team:create }
    requirements:
        _method:  GET

organization_team_delete:
    pattern:  /{slug}/{user}/team/deleted
    defaults: { _controller: TempoProjectBundle:Team:delete }

organization_show:
    pattern:  /{slug}
    defaults: { _controller: TempoProjectBundle:Organization:show }
    requirements:
        _method:  GET