project_home:
    pattern:  /
    defaults: { _controller: TempoProjectBundle:Project:dashboard }

project_organization_list:
    pattern:  /{organization}/list
    defaults: { _controller: TempoProjectBundle:Project:list }

project_new:
    pattern:  /{organization}/new
    defaults: { _controller: TempoProjectBundle:Project:new }

project_create:
    pattern:  /{organization}/create
    defaults: { _controller: TempoProjectBundle:Project:create }

project_edit:
    pattern:  /{slug}/edit
    defaults: { _controller: TempoProjectBundle:Project:edit }

project_update:
    pattern:  /{slug}/update
    defaults: { _controller: TempoProjectBundle:Project:update }
    requirements: { _method: post }

project_delete:
    pattern:  /{slug}/delete
    defaults: { _controller: TempoProjectBundle:Project:delete }

project_team_add:
    pattern:  /{slug}/team/add
    defaults: { _controller: TempoProjectBundle:Team:add }

project_team_create:
    pattern:  /{slug}/team/create
    defaults: { _controller: TempoProjectBundle:Team:create }
    requirements:
        _method:  GET

project_team_delete:
    pattern:  /{slug}/team/delete
    defaults: { _controller: TempoProjectBundle:Team:delete }

project_provider_list:
    pattern:  /{slug}/provider/list
    defaults: { _controller: TempoActivityBundle:Provider:list }

project_provider_update:
    pattern:  /{slug}/provider/update/{provider}
    defaults: { _controller: TempoActivityBundle:Provider:update }

project_version:
    pattern: /{slug}/version
    defaults: { _controller: TempoProjectBundle:Project:version }

project_generate_token:
    pattern: /{slug}/generate-token
    defaults: { _controller: TempoProjectBundle:Project:generateToken }

project_show:
    pattern:  /{slug}
    defaults: { _controller: TempoProjectBundle:Project:show }