project_home:
    pattern:  /
    defaults: { _controller: TempoProjectBundle:Project:dashboard }

project_organization_list:
    pattern:  /{slug}/list
    defaults: { _controller: TempoProjectBundle:Project:list }

project_create:
    pattern:  /{organization}/update
    defaults: { _controller: TempoProjectBundle:Project:create }
    requirements:
        slug: "\w+\/\w+"

project_update:
    pattern:  /{slug}/update
    defaults: { _controller: TempoProjectBundle:Project:update }
    requirements:
        _method: get|post
        slug: "\w+\/\w+"

project_delete:
    pattern:  /{slug}/delete
    defaults: { _controller: TempoProjectBundle:Project:delete }
    requirements:
        slug: "\w+\/\w+"

project_team_add:
    pattern:  /{slug}/team/add
    defaults: { _controller: TempoMainBundle:Frontend/Team:add }
    requirements:
        slug: "\w+\/\w+"

project_team_create:
    pattern:  /{slug}/team/create
    defaults: { _controller: TempoMainBundle:Frontend/Team:create }
    requirements:
        _method:  GET
        slug: "\w+\/\w+"

project_team_delete:
    pattern:  /{slug}/team/delete
    defaults: { _controller: TempoMainBundle:Frontend/Team:delete }
    requirements:
        slug: "\w+\/\w+"

project_provider_list:
    pattern:  /{slug}/provider/list
    defaults: { _controller: TempoProjectBundle:Provider:list }
    requirements:
        slug: "\w+\/\w+"

project_provider_update:
    pattern:  /{slug}/provider/update/{provider}
    defaults: { _controller: TempoProjectBundle:Provider:update }
    requirements:
        slug: "\w+\/\w+"

project_version:
    pattern: /{slug}/version
    defaults: { _controller: TempoProjectBundle:Project:version }
    requirements:
        slug: "\w+\/\w+"

project_activity_list:
    pattern: /{slug}/activity/list/{type}
    defaults:
        _controller: TempoProjectBundle:Activity:list
    options:
      expose: true

project_show:
    pattern:  /{slug}
    defaults: { _controller: TempoProjectBundle:Project:show, _format: html  }
    requirements:
      slug: "\w+\/\w+"