Tempo\Bundle\ProjectBundle\Model\Project:
    exclusion_policy: all
    properties :
      id:
        expose: true
      name:
        expose: true
      slug:
        expose: true
      description:
        expose: true