notification_dashboard:
    path:  /
    defaults: { _controller: "TempoAppBundle:Notification:dashboard" }

notification_read:
    path:  /{date}/show
    defaults: { _controller: "TempoAppBundle:Notification:state" }

notification_unread:
    path:  /{date}/show
    defaults: { _controller: "TempoAppBundle:Notification:state" }

notification_clear:
    path:  /clear
    defaults: { _controller: "TempoAppBundle:Notification:clear" }
