organization_create:
    path:  /create
    defaults: { _controller: TempoAppBundle:Organization:create }
    requirements:
        _method:  GET|POST

organization_update:
     path:  /{slug}/update
     defaults: { _controller: TempoAppBundle:Organization:update }
     requirements:
        _method:  GET|POST

organization_delete:
    path:  /{slug}/delete
    defaults: { _controller: TempoAppBundle:Organization:delete }

organization_team_add:
    path:  /{slug}/team/add
    defaults: { _controller: TempoAppBundle:Team:add }

organization_team_create:
    path:  /{slug}/team/create
    defaults: { _controller: TempoAppBundle:Team:create }
    requirements:
        _method:  GET

organization_team_delete:
    path:  /{slug}/{user}/team/deleted
    defaults: { _controller: TempoAppBundle:Team:delete }

organization_show:
    path:  /{slug}
    defaults: { _controller: TempoAppBundle:Organization:show, _format: html }
    requirements:
        _method:  GET
