organization_create:
   path:  /create
   defaults: { _controller: TempoAppBundle:Organization:create }
   methods: [GET, POST]

organization_update:
    path:  /{slug}/update
    defaults: { _controller: TempoAppBundle:Organization:update }
    methods: [GET, POST]

organization_delete:
    path:  /{slug}/delete
    defaults: { _controller: TempoAppBundle:Organization:delete }

organization_team_add:
    path:  /{slug}/team/add-member
    defaults: { _controller: TempoAppBundle:Access:add }

organization_team_create:
    path:  /{slug}/team/create
    defaults: { _controller: TempoAppBundle:Access:create }
    methods: [GET]

organization_team_delete:
    path:  /{slug}/{user}/team/deleted
    defaults: { _controller: TempoAppBundle:Access:delete }

organization_show:
    path:  /{slug}
    defaults: { _controller: TempoAppBundle:Organization:show, _format: html }
    methods:  [GET]
