user_profile_edit:
   pattern:  /edit
   defaults: { _controller: TempoAppBundle:Profile:edit }

user_profile_picture:
   pattern:  /edit/picture
   defaults: { _controller: TempoAppBundle:Profile:picture }

user_profile_password:
  pattern:  /edit/password
  defaults: { _controller: FOSUserBundle:ChangePassword:changePassword }
  requirements:
    _method:  GET|POST

user_profile_update:
   pattern:  /edit/update
   defaults: { _controller: TempoAppBundle:Profile:update }

user_profile_settings:
   pattern: /edit/settings
   defaults: { _controller: TempoAppBundle:Profile:setting }

user_profile_token:
    pattern: /generate-token
    defaults: { _controller: TempoAppBundle:Profile:generateToken }

user_profile_show:
   pattern: /{slug}
   defaults: { _controller: TempoAppBundle:Profile:show }

fos_user_profile_show:
   pattern: /edit
   defaults: {  _controller: TempoAppBundle:Profile:edit }
