project_home:
    path:  /
    defaults: { _controller: TempoAppBundle:Project:dashboard }

project_organization_list:
    path:  /{slug}/list
    defaults: { _controller: TempoAppBundle:Project:list }

project_create:
    path:  /{organization}/create
    defaults: { _controller: TempoAppBundle:Project:create }

project_update:
    path:  /{slug}/update
    defaults: { _controller: TempoAppBundle:Project:update }
    requirements:
        _method: get|post
        slug: ".+"

project_delete:
    path:  /{slug}/delete
    defaults: { _controller: TempoAppBundle:Project:delete }
    requirements:
        slug: ".+"

project_team_add:
    path:  /{slug}/team/add
    defaults: { _controller: TempoAppBundle:Team:add }
    requirements:
        slug: ".+"

project_team_create:
    path:  /{slug}/team/create
    defaults: { _controller: TempoAppBundle:Team:create }
    requirements:
        _method:  GET
        slug: ".+"

project_team_delete:
    path:  /{slug}/team/delete
    defaults: { _controller: TempoAppBundle:Team:delete }
    requirements:
        slug: ".+"

project_provider_list:
    path:  /{slug}/provider/list
    defaults: { _controller: TempoAppBundle:Provider:list }
    requirements:
        slug: ".+"

project_provider_update:
    path:  /{slug}/provider/update/{provider}
    defaults: { _controller: TempoAppBundle:Provider:update }
    requirements:
        slug: ".+"

project_version:
    path: /{slug}/version
    defaults: { _controller: TempoAppBundle:Project:version }
    requirements:
        slug: ".+"

project_activity_list:
    path: /{slug}/activity/list/{type}
    defaults:
        _controller: TempoAppBundle:Activity:list
    options:
      expose: true

_project_settings:
    path: /settings
    methods: [GET]
    defaults:
        _controller: sylius.controller.settings:updateAction
        namespace: general
        template: TempoAppBundle:Backend/Settings:general.html.twig

project_show:
    path:  /{slug}
    defaults: { _controller: TempoAppBundle:Project:show, _format: html }
    requirements:
      slug: ".+"
