api_room_show:
    pattern:  /room/{slug}
    defaults: { _controller: TempoAppBundle:Room:getRoom }
    requirements:

api_room_all:
  pattern: /room/all
  defaults: { _controller: TempoAppBundle:Room:getRoom }
