api_room_show:
    path:  /room/{slug}
    defaults: { _controller: TempoAppBundle:Api/Room:getRoom }
    requirements:

api_room_all:
  path: /room/all
  defaults: { _controller: TempoAppBundle:Api/Room:getRoom }
