room_list:
    path: /list
    defaults: { _controller: TempoAppBundle:Room:list }

room_create:
    path: /create
    defaults: { _controller: TempoAppBundle:Room:list }

room_update:
    path: /{id}/update
    defaults: { _controller: TempoAppBundle:Room:update}
    
room_delete:
    path: /{id}/delete
    defaults: { _controller: TempoAppBundle:Room:delete}
    
room_leave:
    path:  /{id}/team/{user}/delete
    defaults: { _controller: TempoAppBundle:Access:delete }
    
    
