room_show:
    path:  /{slug}
    defaults: { _controller: TempoAppBundle:Room:getRoom }

room_list:
    path: /list
    defaults: { _controller: TempoAppBundle:Room:getRooms }

room_update:
    path: /{id}/update
    defaults: { _controller: TempoAppBundle:Room:update, _format: html }
