room_show:
    pattern:  /{slug}
    defaults: { _controller: TempoAppBundle:Room:getRoom }

room_list:
    pattern: /list
    defaults: { _controller: TempoAppBundle:Room:getRooms }

room_update:
    pattern: /{id}/update
    defaults: { _controller: TempoAppBundle:Room:update, _format: html }
