timesheet:
    path:  /
    defaults: { _controller: "TempoAppBundle:Timesheet:dashboard" }

timesheet_show:
    path:  /{project}/{date}/show
    defaults: { _controller: "TempoAppBundle:Timesheet:show" }

timesheet_create:
    path:  /{project}/create
    defaults: { _controller: TempoAppBundle:Timesheet:create }
    requirements: { _method: POST }

timesheet_update:
    path:  /{id}/update
    defaults: { _controller: "TempoAppBundle:Timesheet:update" }
    requirements: { _method: POST }

timesheet_delete:
    path:  /{id}/delete
    defaults: { _controller: "TempoAppBundle:Timesheet:delete" }
    requirements: { _method: POST }

timesheet_validation:
    path: /validation
    defaults: { _controller: "TempoAppBundle:Timesheet:validation" }

timesheet_export_pdf:
    path:  /export/pdf
    defaults: { _controller: "TempoAppBundle:Timesheet:exportPDF" }

timesheet_export_csv:
    path:  /export/csv
    defaults: { _controller: "TempoAppBundle:Timesheet:exportCSV" }
