user_login:
    path: /login
    defaults: { _controller: "TempoAppBundle:Security:login" }

user_login_check:
    path: /login_check
    defaults: { _controller: "TempoAppBundle:Security:check" }

user_logout:
    path: /logout
    defaults: { _controller: "TempoAppBundle:Security:logout" }

user_register:
    path: /register
    defaults: { _controller: "TempoAppBundle:Security:register"}

api_user_autocomplete:
    path: /api/{version}/users/search/{username}
    defaults:
        _controller: "TempoAppBundle:Api/User:autocomplete"
        version:  internal
        username:  null

api_user_current:
    path: /api/{version}/users/current
    defaults:
        _controller: "TempoAppBundle:Api/User:current"
        version:  internal

user_notification:
    resource: "@TempoAppBundle/Resources/config/routing/notification.yml"
    prefix: /notifications

user_profile:
    resource: "@TempoAppBundle/Resources/config/routing/profile.yml"
    prefix: /profile

user_resetting_reset:
    path: /user/resetting
    defaults:
        _controller: "TempoAppBundle:Resetting:reset"
    methods: [GET|POST]

user_resetting_validate:
    path: /user/resetting/{token}
    defaults:
        _controller: "TempoAppBundle:Resetting:resetValidate"
    methods:  [GET,POST]

user_admin:
    resource: "@TempoAppBundle/Resources/config/routing/admin/user.yml"
    prefix: /admin/users

user_invite_resent:
    path: /user/invite/{id}
    defaults:
        _controller: "TempoAppBundle:Access:invite"
